/* accessories-data.js - generated by scripts/sync-accessories.ps1. Do not edit by hand. */
window.MM_ACCESSORIES_DATA = {
  generatedAt: "2026-09-23 10:20",
  sizes: [

  ],
  colors: [

  ],
  items: [

  ]
};
