/* sellers-data.js - generated by scripts/sync-sellers.ps1. Do not edit by hand. */
window.MM_SELLERS_DATA = {
  sellers: {
    "koren": { displayName: "KOREN", legalName: "מידן נציגויות בע\"מ", companyId: "511163206", address: "סוקולוב 67, רמת השרון", phone: "03-5400401", tagline: "הבית שלך למוצרי חשמל" }
  },
  brands: {
    "LG": { name: "LG", importerName: "ח.י אלקטרוניקה \\ HYE" },
    "SAMSUNG": { name: "SAMSUNG", importerName: "ניופרו \\ NEWPRO" },
    "TCL": { name: "TCL", importerName: "סי דאטה \\ C-DATA" }
  }
};
